// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthenticatedUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Category struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt string `json:"createdAt"`
}

type CreateCategoryInput struct {
	Name   string  `json:"name"`
	Slug   string  `json:"slug"`
	Parent *string `json:"parent,omitempty"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateCategoryInput struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Slug   string  `json:"slug"`
	Parent *string `json:"parent,omitempty"`
}

type UpdateUserInput struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
